name: Deploy ChildCare App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}


      - name: Build and push Docker images
        run: |
          docker build -t louisquinn296/childcare-app:latest ./ChildCareCalendarSolution
          docker push louisquinn296/childcare-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker pull louisquinn296/childcare-app:latest
            docker compose down
            docker compose up -d
